version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_PATH: /app/data/mydb.sqlite
      PORT: 3000
    ports:
      - 3000:3000
    command: npm run dev